# secrets.example.toml
# Copiar este archivo a secrets.toml y configurar valores reales

[api_keys]
# Claves de APIs de noticias
google_news_api_key = "your_google_news_api_key_here"
bing_news_api_key = "your_bing_news_api_key_here"
newsapi_key = "your_newsapi_key_here"

[database]
# Configuración de base de datos (si se implementa en el futuro)
host = "localhost"
port = 5432
username = "vision_user"
password = "your_secure_password_here"
database_name = "vision_db"

[security]
# Configuración de seguridad
secret_key = "your_secret_key_here"
jwt_secret = "your_jwt_secret_here"
encryption_key = "your_encryption_key_here"

[monitoring]
# Configuración de monitoreo
prometheus_port = 9108
grafana_port = 3000
alert_email = "alerts@vision.com"

[external_services]
# Servicios externos
openai_api_key = "your_openai_api_key_here"
huggingface_token = "your_huggingface_token_here"






