[global]
# Configuraci贸n global de Streamlit
showWarningOnDirectExecution = false

[server]
# Configuraci贸n del servidor
port = 8501
address = "localhost"
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
# Configuraci贸n del navegador
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
# Tema por defecto
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[logger]
# Configuraci贸n de logs
level = "info"
messageFormat = "%(asctime)s %(message)s"






