# VISION PREMIUM - CONFIGURACIÓN DE SECRETS
# IMPORTANTE: Reemplaza estas keys con las tuyas reales

[secrets]
# NewsAPI (https://newsapi.org/register)
NEWS_API_KEY = "tu_api_key_aqui"

# GNews (https://gnews.io/)
GNEWS_API_KEY = "tu_api_key_aqui"

# Bing News Search (Microsoft)
BING_API_KEY = "tu_api_key_aqui"

# Configuración adicional
DEMO_MODE = true
ENABLE_REAL_APIS = false








